import type { FastifyPluginAsync } from "fastify";
import { healthRoutes } from "./health.js";
import { blobRoutes } from "./blobs.js";
import { eventRoutes } from "./events.js";
import { documentRoutes } from "./documents.js";
import { cmsRoutes } from "./cms.js";
import { gardenRoutes } from "./gardens.js";
import { publicRoutes } from "./public.js";
import { searchRoutes } from "./search.js";
import { sessionRoutes } from "./sessions.js";
import { jobRoutes } from "./jobs.js";
import { metricsRoutes } from "./metrics.js";
import { graphRoutes } from "./graph.js";
import { lakeRoutes } from "./lakes.js";
import { translationRoutes } from "./translations.js";
import { labelsRoutes } from "./labels.js";
import { tenantsRoutes } from "./tenants.js";
import { exportRoutes } from "./exports.js";
import { reviewRoutes } from "./reviews.js";
import { mongoRoutes } from "./mongo.js";
import { stateRoutes } from "./state.js";
import { openApiRoutes } from "./openapi.js";

export const v1Routes: FastifyPluginAsync = async (app) => {
  await app.register(healthRoutes);
  await app.register(blobRoutes);
  await app.register(eventRoutes);
  await app.register(documentRoutes);
  await app.register(cmsRoutes);
  await app.register(gardenRoutes);
  await app.register(publicRoutes);
  await app.register(searchRoutes);
  await app.register(sessionRoutes);
  await app.register(jobRoutes);
  await app.register(metricsRoutes);
  await app.register(graphRoutes);
  await app.register(lakeRoutes);
  await app.register(translationRoutes);
  await app.register(labelsRoutes, { prefix: "/labels" });
  await app.register(tenantsRoutes, { prefix: "/tenants" });
  await app.register(exportRoutes, { prefix: "/export" });
  await app.register(reviewRoutes, { prefix: "/reviews" });
  await app.register(mongoRoutes, { prefix: "/mongo" });
  await app.register(stateRoutes);
  await app.register(openApiRoutes);
};
