apiVersion: apps/v1
kind: Deployment
metadata:
  name: openplanner
spec:
  strategy:
    $patch: replace
    type: Recreate
  template:
    spec:
      containers:
        - name: openplanner
          resources:
            requests:
              cpu: 150m
              memory: 384Mi
            limits:
              cpu: 750m
              memory: 1Gi