apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  mongod.conf: |
    net:
      port: 27017
      bindIpAll: true

    replication:
      replSetName: rs0

    security:
      keyFile: /workdir/mongodb-keyfile

    setParameter:
      mongotHost: mongot:27028
      useGrpcForSearch: true

    storage:
      dbPath: /data/db

    systemLog:
      destination: file
      path: /proc/1/fd/1
      logAppend: true
