export const EVENT_BUS_CONFIG = {
  DEFAULT_BATCH_SIZE: 100,
  DEFAULT_MAX_IN_FLIGHT: 1000,
  DEFAULT_ACK_TIMEOUT_MS: 30000,
  DEFAULT_MAX_ATTEMPTS: 5,
  CLEANUP_INTERVAL_MS: 60000, // 1 minute
  MAX_EVENT_AGE_MS: 3600000, // 1 hour
} as const;

export type EventBusConfig = typeof EVENT_BUS_CONFIG;
